### ISSUE TITLE
Restauration et sauvegarde

### ISSUE THREAD

**Issue by Titom59** [motioneye-project/motioneye.eo#9]
Salut, je viens de découvrir ce fork de motioneye quel plaisir quand c'est dans notre langue.

Je tournais avec la version de motioneye classique avant j'ai tenter de restaurer ma sauvegarde venant de la pour récupérer toute ma config sur le fork, mais j'ai un message `Impossible de restaurer la configuration!`
Je pensais bien évidement à un problème de compatibilité de version, j'ai donc essayer de restaurer une sauvegarde venant du fork mais j'ai le même message.

Merci pour votre aide.

**Comment by jmichault** [comment]
Bonsoir,
Je viens de publier une mise à jour sur pypi.
Merci de tester et de me faire un retour.

**Comment by Titom59** [comment]
Et bien merci beaucoup pour votre réactivité, ça fonctionne nickel.

**Comment by jmichault** [comment]
Merci du retour.
Je ferme.
